name: Release

on:
  release:
    types: [created]

jobs:
  multibuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: "1.1.15"
    - name: Build wheels
      run: |
        poetry build
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: dist

  release:
    name: Release
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    needs: [ multibuild ]
    permissions:
       # IMPORTANT: this permission is mandatory for trusted publishing
       id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
